### ISSUE TITLE
Build-time error. 

### ISSUE THREAD

**Issue by HarshitRuwali** [Hardikkr/Oblique#1]
Error in Android studio while running in iPhone simulator: 
```
lib/Home.dart:132:29: Error: No named parameter with the name 'dropdownColor'.
                            dropdownColor: Colors.white,
                            ^^^^^^^^^^^^^
../../Developer/flutter/packages/flutter/lib/src/material/dropdown.dart:784:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.
```

Error in Android studio while running in Android Simulator: 
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/harshitruwali/Desktop/Oblique/android/settings.gradle' line: 15

* What went wrong:
A problem occurred evaluating settings 'android'.
> Could not read script '/Users/harshitruwali/Developer/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

While running `flutter doctor -v` does not give any error.  
```
harshitruwali@Harshits-MacBook-Pro oblique % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/harshitruwali/Developer/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/harshitruwali/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by Hardikkr** [comment]
In the "Home.dart" page, try to comment or remove line no. 132 (dropdownColor: Colors.white,).
I think this will work.
I've also corrected this mistake in my project.

**Comment by HarshitRuwali** [comment]
Still throwing the same error for android.
But in iPhone simulator, app builds and launches for a second and closes.

**Comment by HarshitRuwali** [comment]
It's working after a few changes in the plist files in the company domain name. 
Change the default `com.example.hire ` to the desired one. 
And then run:
`flutter create --org com.'your-name/org-name'.hire`
And then create using 
`flutter create .`
